### PR TITLE
Updade jest to 24, and update tests

### PR DESCRIPTION
**Pull request by polem**
Hi, i'd like to use jest 24 with my serverless projet, here is a PR, i updated the test, everything is green :)

### CODE REVIEW

**Comment by polem** [comment]
Up @artoliukkonen :)

**Comment by dhm116** [comment]
If you'd like to get to Jest v24 and the latest Serverless, you could try out https://github.com/fireeye/jest-environment-serverless - it's actually able to execute the tests quite a bit faster as well since it's not rerunning Jest separately.

**Comment by aaronmcadam** [comment]
This is blocking me from using this project. I need to use Jest 24 because I'm depending on Babel 7.

Here's the error I get:

```
Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel
```

If I hack the package.json to bump the Jest version, it fixes it.

**Comment by aaronmcadam** [comment]
@polem Were there any reasons why this PR was not merged?

**Comment by polem** [comment]
@aaronmcadam no news from the maintener sorry

**Comment by aaronmcadam** [comment]
Thanks @polem. That's a shame. Looks like we'll have to use https://www.npmjs.com/package/patch-package

**Comment by aaronmcadam** [comment]
I wonder if these plugin repos should be moved to the serverless organisation anyway

**Comment by dhm116** [comment]
*cough* *cough* *wink* *wink* https://github.com/fireeye/jest-environment-serverless

**Comment by KariHe** [comment]
#30

**Pull request merged**
