### PR TITLE
Upgrade Jest to latest (v23.6)

### PR DESCRIPTION
**Pull request by dhm116**
This should resolve the open issues with upgrading the Jest dependency, since it's extremely out-of-date. I also updated the serverless framework to the current latest.

I tried to keep the changes to the minimum required to get the tests passing. Anything else were just artifacts of VS Code running the `eslint` config (_mostly just in `__tests__/test-utils.js`_)

Please let me know if there's anything else I can update for this PR to be merged in. Thanks!

### CODE REVIEW

**Comment by dhm116** [comment]
This is probably going to be a breaking change since [Jest v22 drops support for Node 4](https://jestjs.io/blog/2017/12/18/jest-22#good-bye-node-4-welcome-jsdom-11)

**Comment by pawdro** [comment]
Can it be merged asap? :) @laardee

**Comment by laardee** [comment]
lgtm :+1: @artoliukkonen can you review this?

**Comment by jplock** [comment]
Any idea if this will be merged and released?

**Comment by artoliukkonen** [comment]
Thanks for the contribution, and sorry we are lagging behind with merging & releasing these changes. Will definitely try to improve on this. Releasing new version to NPM soon.

**Comment by dhm116** [comment]
Thanks a ton! 👍

**Pull request merged**
